apiVersion: v1
kind: Secret
metadata: 
  name: mysecret
type: Opaque
data: 
  mongo-user: c2FpcmFt       # Base64-encoded value for 'admin'
  password: c2FpcmFtMTIz  # Base64-encoded value for 'password'
